export const currencyOptions = [
  { symbol: 'USD', name: 'American Dollar (USD)' },
  { symbol: 'GBP', name: 'British Pound (GBP)' },
  { symbol: 'BGN', name: 'Bulgarian Lev (BGN)' },
  { symbol: 'CAD', name: 'Canadian Dollar (CAD)' },
  { symbol: 'CNY', name: 'Chinese Yuan (CNY)' },
  { symbol: 'CZK', name: 'Czech koruna (CZK)' },
  { symbol: 'EUR', name: 'Euro (EUR)' },
  { symbol: 'HUF', name: 'Hungarian Forint (HUF)' },
  { symbol: 'JPY', name: 'Japanese Yen (JPY)' },
  { symbol: 'PLN', name: 'Polish Zloty (PLN)' },
  { symbol: 'RUB', name: 'Russian Rubble (RUB)' },
  { symbol: 'SEK', name: 'Swedish korona (SEK)' },
  { symbol: 'CHF', name: 'Swiss Franc (CHF)' },
  { symbol: 'TRY', name: 'Turkish Lira (TRY)' },
];
